parameters:
#    base.example.class: Administration\BaseBundle\Example

services:
#    base.example:
#        class: %base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
